// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sqrtmNewt2
arma::mat sqrtmNewt2(arma::mat& C, arma::mat& sqrt0, const double& errTol);
RcppExport SEXP SpiecEasi_sqrtmNewt2(SEXP CSEXP, SEXP sqrt0SEXP, SEXP errTolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type sqrt0(sqrt0SEXP);
    Rcpp::traits::input_parameter< const double& >::type errTol(errTolSEXP);
    __result = Rcpp::wrap(sqrtmNewt2(C, sqrt0, errTol));
    return __result;
END_RCPP
}
// SOFTTHRESH2
arma::sp_mat SOFTTHRESH2(arma::mat& Sig, const float& lambda, const bool& shrinkDiag);
RcppExport SEXP SpiecEasi_SOFTTHRESH2(SEXP SigSEXP, SEXP lambdaSEXP, SEXP shrinkDiagSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type Sig(SigSEXP);
    Rcpp::traits::input_parameter< const float& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const bool& >::type shrinkDiag(shrinkDiagSEXP);
    __result = Rcpp::wrap(SOFTTHRESH2(Sig, lambda, shrinkDiag));
    return __result;
END_RCPP
}
// softSVT2
arma::mat softSVT2(arma::mat& M, int k, double beta);
RcppExport SEXP SpiecEasi_softSVT2(SEXP MSEXP, SEXP kSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    __result = Rcpp::wrap(softSVT2(M, k, beta));
    return __result;
END_RCPP
}
// ADMM
List ADMM(const arma::mat& SigmaO, const double& lambda, arma::mat& I, arma::mat& Lambda, arma::mat& Y, double beta, int r, double mu, const double& eta, const double& muf, const int& maxiter, const double& newtol, const double& tol, const double& over_relax_par, bool shrinkDiag);
RcppExport SEXP SpiecEasi_ADMM(SEXP SigmaOSEXP, SEXP lambdaSEXP, SEXP ISEXP, SEXP LambdaSEXP, SEXP YSEXP, SEXP betaSEXP, SEXP rSEXP, SEXP muSEXP, SEXP etaSEXP, SEXP mufSEXP, SEXP maxiterSEXP, SEXP newtolSEXP, SEXP tolSEXP, SEXP over_relax_parSEXP, SEXP shrinkDiagSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaO(SigmaOSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double& >::type muf(mufSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const double& >::type newtol(newtolSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double& >::type over_relax_par(over_relax_parSEXP);
    Rcpp::traits::input_parameter< bool >::type shrinkDiag(shrinkDiagSEXP);
    __result = Rcpp::wrap(ADMM(SigmaO, lambda, I, Lambda, Y, beta, r, mu, eta, muf, maxiter, newtol, tol, over_relax_par, shrinkDiag));
    return __result;
END_RCPP
}
// MATAVE2
arma::mat MATAVE2(arma::mat A, arma::mat B);
RcppExport SEXP SpiecEasi_MATAVE2(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    __result = Rcpp::wrap(MATAVE2(A, B));
    return __result;
END_RCPP
}
// MATAVE3
arma::mat MATAVE3(arma::mat A, arma::mat B, arma::mat C);
RcppExport SEXP SpiecEasi_MATAVE3(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    __result = Rcpp::wrap(MATAVE3(A, B, C));
    return __result;
END_RCPP
}
// sqrtmNewt
arma::mat sqrtmNewt(arma::mat C, SEXP sqrt0, double errTol);
RcppExport SEXP SpiecEasi_sqrtmNewt(SEXP CSEXP, SEXP sqrt0SEXP, SEXP errTolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sqrt0(sqrt0SEXP);
    Rcpp::traits::input_parameter< double >::type errTol(errTolSEXP);
    __result = Rcpp::wrap(sqrtmNewt(C, sqrt0, errTol));
    return __result;
END_RCPP
}
// solveCpp
arma::mat solveCpp(arma::mat C, arma::mat X);
RcppExport SEXP SpiecEasi_solveCpp(SEXP CSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    __result = Rcpp::wrap(solveCpp(C, X));
    return __result;
END_RCPP
}
// SOFTTHRESH
arma::sp_mat SOFTTHRESH(arma::mat Sig, float lambda, bool shrinkDiag);
RcppExport SEXP SpiecEasi_SOFTTHRESH(SEXP SigSEXP, SEXP lambdaSEXP, SEXP shrinkDiagSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type Sig(SigSEXP);
    Rcpp::traits::input_parameter< float >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type shrinkDiag(shrinkDiagSEXP);
    __result = Rcpp::wrap(SOFTTHRESH(Sig, lambda, shrinkDiag));
    return __result;
END_RCPP
}
// softSVT
List softSVT(arma::mat M, float tau, int k);
RcppExport SEXP SpiecEasi_softSVT(SEXP MSEXP, SEXP tauSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< float >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    __result = Rcpp::wrap(softSVT(M, tau, k));
    return __result;
END_RCPP
}
