# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sqrtmNewt2 <- function(C, sqrt0, errTol) {
    .Call('SpiecEasi_sqrtmNewt2', PACKAGE = 'SpiecEasi', C, sqrt0, errTol)
}

SOFTTHRESH2 <- function(Sig, lambda, shrinkDiag = TRUE) {
    .Call('SpiecEasi_SOFTTHRESH2', PACKAGE = 'SpiecEasi', Sig, lambda, shrinkDiag)
}

softSVT2 <- function(M, k, beta = 0) {
    .Call('SpiecEasi_softSVT2', PACKAGE = 'SpiecEasi', M, k, beta)
}

ADMM <- function(SigmaO, lambda, I, Lambda, Y, beta = 0, r = 0L, mu = 0, eta = 4/5, muf = 1e-6, maxiter = 500L, newtol = 1e-5, tol = 1e-5, over_relax_par = 1.6, shrinkDiag = TRUE) {
    .Call('SpiecEasi_ADMM', PACKAGE = 'SpiecEasi', SigmaO, lambda, I, Lambda, Y, beta, r, mu, eta, muf, maxiter, newtol, tol, over_relax_par, shrinkDiag)
}

MATAVE2 <- function(A, B) {
    .Call('SpiecEasi_MATAVE2', PACKAGE = 'SpiecEasi', A, B)
}

MATAVE3 <- function(A, B, C) {
    .Call('SpiecEasi_MATAVE3', PACKAGE = 'SpiecEasi', A, B, C)
}

sqrtmNewt <- function(C, sqrt0, errTol = 1e-3) {
    .Call('SpiecEasi_sqrtmNewt', PACKAGE = 'SpiecEasi', C, sqrt0, errTol)
}

solveCpp <- function(C, X) {
    .Call('SpiecEasi_solveCpp', PACKAGE = 'SpiecEasi', C, X)
}

SOFTTHRESH <- function(Sig, lambda, shrinkDiag = TRUE) {
    .Call('SpiecEasi_SOFTTHRESH', PACKAGE = 'SpiecEasi', Sig, lambda, shrinkDiag)
}

softSVT <- function(M, tau = 0, k = 0L) {
    .Call('SpiecEasi_softSVT', PACKAGE = 'SpiecEasi', M, tau, k)
}

