# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sqrtmNewt2 <- function(C, sqrt0, errTol) {
    .Call('_SpiecEasi_sqrtmNewt2', PACKAGE = 'SpiecEasi', C, sqrt0, errTol)
}

SOFTTHRESH2 <- function(Sig, lambda, shrinkDiag = TRUE) {
    .Call('_SpiecEasi_SOFTTHRESH2', PACKAGE = 'SpiecEasi', Sig, lambda, shrinkDiag)
}

svdPowSym <- function(U, d, V, A, k, q) {
    invisible(.Call('_SpiecEasi_svdPowSym', PACKAGE = 'SpiecEasi', U, d, V, A, k, q))
}

svdPowSym2 <- function(M, k) {
    .Call('_SpiecEasi_svdPowSym2', PACKAGE = 'SpiecEasi', M, k)
}

softSVT3 <- function(M, k, beta = 0) {
    .Call('_SpiecEasi_softSVT3', PACKAGE = 'SpiecEasi', M, k, beta)
}

softSVT2 <- function(M, k, beta = 0) {
    .Call('_SpiecEasi_softSVT2', PACKAGE = 'SpiecEasi', M, k, beta)
}

SVD2 <- function(M) {
    .Call('_SpiecEasi_SVD2', PACKAGE = 'SpiecEasi', M)
}

ADMM <- function(SigmaO, lambda, I, Lambda, Y, beta = 0, r = 0L, mu = 0, eta = 4/5, muf = 1e-6, maxiter = 500L, newtol = 1e-5, tol = 1e-5, over_relax_par = 1.6, shrinkDiag = TRUE) {
    .Call('_SpiecEasi_ADMM', PACKAGE = 'SpiecEasi', SigmaO, lambda, I, Lambda, Y, beta, r, mu, eta, muf, maxiter, newtol, tol, over_relax_par, shrinkDiag)
}

sqrtmNewt <- function(C, sqrt0, errTol = 1e-3) {
    .Call('_SpiecEasi_sqrtmNewt', PACKAGE = 'SpiecEasi', C, sqrt0, errTol)
}

solveCpp <- function(C, X) {
    .Call('_SpiecEasi_solveCpp', PACKAGE = 'SpiecEasi', C, X)
}

SOFTTHRESH <- function(Sig, lambda, shrinkDiag = TRUE) {
    .Call('_SpiecEasi_SOFTTHRESH', PACKAGE = 'SpiecEasi', Sig, lambda, shrinkDiag)
}

softSVT <- function(M, tau = 0, k = 0L) {
    .Call('_SpiecEasi_softSVT', PACKAGE = 'SpiecEasi', M, tau, k)
}

